DB: handle NULL in auc.algo
The algo column is defined as:

    algo = Column(
    	String(20),
	default='3',
	doc='2G Authentication Algorithm (1 = Comp128v1, 2 = Comp128v2, 3 = Comp128v3, All Other= 3G auth with 2g keys from 3G Milenage)',
    )

Notably:
* It does not have nullable=False, meaning that NULL is allowed.
* The default of 3 is not set at CREATE TABLE time, for that
  server_default would need to be used [1].

Handle the case that users may fill the database with a script that
leaves the algo field empty and therefore defaults to NULL.

Fix for:
  TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

[1]: https://docs.sqlalchemy.org/en/20/core/defaults.html#sqlalchemy.schema.ColumnDefault