tests/test_Diameter: fix test_A_Instantiate
Add the missing LogTool parameter to Diameter() to fix:
  AttributeError: 'str' object has no attribute 'log'