requirements: upgrade flask for python 3.14 compat
Upgrade flask and flask_restx to the latest versions, which are
compatible with python 3.14. Remove Werkzeug, as flask already depends
on it and so we don't need to manually update its version when updating
the Flask version.

Fix for:
  AttributeError: module 'pkgutil' has no attribute 'get_loader'