tests/test_API: GeoRed_MME: fix patch payloads
Send fields that the API expects, as otherwise the test fails with e.g.:

  JSON Data sent in Geored request: {'imsi': '001001000000020', 'serving_mme': 'test1234'}
  Updating serving MME
  Exception when updating: Traceback (most recent call last):
    File "/home/user/code/osmo-dev/src/pyhss/services/apiService.py", line 2090, in patch
      response_data.append(databaseClient.Update_Serving_MME(imsi=str(json_data['imsi']), serving_mme=json_data['serving_mme'], serving_mme_realm=json_data['serving_mme_realm'], serving_mme_peer=json_data['serving_mme_peer'], propagate=False))
                                                                                                                                                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  KeyError: 'serving_mme_realm'