tests/test_database: create auc: use bytes.hex
The AUC database object expects ki and opc as text string, not as bytes.

Fix for:

    File "/home/user/code/osmo-dev/src/pyhss/tests/test_database.py", line 124, in test_database
      database.Get_Vectors_AuC(auc_id, "air", plmn="12ff")
    File "/home/user/code/osmo-dev/src/pyhss/lib/database.py", line 1592, in Get_Vectors_AuC
      rand, xres, autn, kasme = S6a_crypt.generate_eutran_vector(key_data['ki'], key_data['opc'], key_data['amf'], key_data['sqn'], kwargs['plmn'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/user/code/osmo-dev/src/pyhss/lib/S6a_crypt.py", line 19, in generate_eutran_vector                                                                                                   key = key.encode('utf-8')
            ^^^^^^^^^^
  AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?