requirements.txt: upgrade SQLAlchemy
Fix that starting PyHSS with Python 3.13 fails with the following error
by upgrading to the latest SQLAlchemy 2.0.x version:

AssertionError: Class <class 'sqlalchemy.sql.elements.SQLCoreOperations'> directly inherits TypingOnly but has additional attributes {'__static_attributes__'}.

Related: https://github.com/sqlalchemy/sqlalchemy/issues/11334